Project/Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('products/', include('simpleapp.urls')),
    path('news/', include('news.urls')),
    path('', include('protect.urls')),
    path('sign/', include('sign.urls')),
    path('app/', include('appointment.urls')),
    path('accounts/', include('allauth.urls')),
]

Project/appointment/urls.py
from django.urls import path
from .views import AppointmentView

app_name = 'appointment'

urlpatterns = (
    path('appoint/', AppointmentView.as_view(), name='appointment'),
)

Project/news/urls.py
from django.urls import path
from .views import (NewsList, NewDetail, NewsSearch, NewsCreate, NewsUpdate, NewsDelete)

urlpatterns = [
    path('', NewsList.as_view(), name='news_list'),
    path('<int:pk>', NewDetail.as_view(), name='news_detail'),
    path('search/', NewsSearch.as_view(), name='news_search'),
    path('create/', NewsCreate.as_view(), name='news_create'),
    path('<int:pk>/edit/', NewsUpdate.as_view(), name='news_update'),
    path('<int:pk>/delete/', NewsDelete.as_view(), name='news_create'),
    path('articles/create/', NewsCreate.as_view(), name='article_create'),
    path('articles/<int:pk>/edit/', NewsUpdate.as_view(), name='articles_update'),
    path('articles/<int:pk>/delete/', NewsDelete.as_view(), name='articles_delete'),
    path('news/', NewsList.as_view(), name='news_list'),
]

Project/news/models.py
from django.db import models

from django.db import models
from django.urls import reverse


class News(models.Model):
    news = 'NW'
    article = 'AR'

    Type = [
        (news, 'новость'),
        (article, 'статья')
    ]

    name = models.CharField(max_length=155)
    description = models.TextField()
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='news',
        null=True,
        blank=False,
    )
    release_date = models.DateTimeField(auto_now_add=True)
    article_news = models.CharField(max_length=2, choices=Type, default=news)

    def __str__(self):
        return f'{self.name}, {self.description[:64]}, {self.release_date}'

    def get_absolute_url(self):
        return reverse('news_detail', args=[str(self.id)])


class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.category_name}'

Project/news/forms.py
from .models import News
from django import forms


class NewsForm(forms.ModelForm):
    description = forms.CharField(max_length=55)

    class Meta:
        model = News
        fields = [
            'name',
            'description',
            'category',
        ]

Project/news/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic import (ListView, DetailView, UpdateView, DeleteView)
from django.views.generic.edit import CreateView
from .filters import NewsFilter
from .forms import NewsForm
from .models import News
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.views.generic import TemplateView
from rest_framework.permissions import IsAuthenticatedOrReadOnly


class NewsList(ListView):
    model = News
    ordering = 'name'
    template_name = 'news.html'
    context_object_name = 'news'
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = NewsFilter(self.request.GET, queryset)
        return self.filterset.qs


class NewDetail(DetailView):
    model = News
    template_name = 'new.html'
    context_object_name = 'new'


class NewsSearch(ListView):
    model = News
    ordering = 'name'
    template_name = 'news_search.html'
    context_object_name = 'news'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = NewsFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class NewsCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_news',)
    form_class = NewsForm
    model = News
    template_name = 'news_create.html'

    def form_valid(self, form):
        new = form.save(commit=False)
        if self.request.path == '/news/articles/create/':
            new.article_news = 'AR'
        new.save()
        return super().form_valid(form)


class NewsUpdate(PermissionRequiredMixin, LoginRequiredMixin,  UpdateView):
    permission_required = ('news.change_news',)
    form_class = NewsForm
    model = News
    template_name = 'news_create.html'


class NewsDelete(DeleteView):
    model = News
    template_name = 'news_delete.html'
    success_url = reverse_lazy('news_list')


class ProtectedView(LoginRequiredMixin, TemplateView):
    model = News
    template_name = 'news_create.html'
    form_class = NewsForm
    login_url = 'news'

Project/templates/main.html
<html>
    <head>
        <title> Simple Signup/Signin app</title>
    </head>
    <body>
        <div>
          <h1><a href="/"> Simple SignUp/SignIn app </a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

Project/templates/make_appointment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Make an appointment</h1>
    <form action="{% url 'appointment:appointment' %}" method="POST">
        {% csrf_token %}
        <label for="client_name">Your name</label>
        <input type="text" name="client_name"><br>
        <label for="message">Short dascription of your issue</label>
        <input type="text" name="message">
        <label for="date">Choose time</label>
        <input type="date" name="date">
        <input type="submit">
    </form>
</body>
</html>

Project/templates/new.html
{% extends 'flatpages/default.html' %}

{% block title %}
New
{% endblock title %}
<h1>{{new}}</h1>
{% block content %}
    <h2> {{ time_now|date:'M d Y'}}</h2>
    <h2>Новости:{{new.name}}</h2>
    <h5>{{new.description}}</h5>
{% endblock content %}

Project/templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filter%}
{% load custom_tags%}

{% block title %}
News
{% endblock title %}


{% block content %}
    <h1>Все новости</h1>
    <h3>{{ time_now|date:'M d Y'}}</h3>
    <hr>
    {% if news %}
        <table>
            <tr>
                <td>Название</td>
                <td>Описание</td>
                <td>Категория</td>
                <td>Тип публикации</td>
            </tr>
            {% for new in news %}
            <tr>
                <td>{{ new.name|truncatechars:10 }}</td>
                <td>{{ new.description| truncatechars:15 }}</td>
                <td>{{ new.category}}</td>
                <td>{{ new.get_article_news_display }}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей пока нет!</h2>
   {% endif %}

    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

Project/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Новости</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Создать">
</form>
{% endblock content %}

Project/templates/news_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Уведомления</title>
</head>
<body>
    <h2>Здравствуйте! Новая <a href="{{ link}}">статья</a>в вашем любимом разделе!</h2>
        <p>{{text}}</p>
</body>
</html>

Project/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Удалить"/>
</form>
{% endblock content %}

Project/templates/news_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filter%}
{% load custom_tags%}

{% block title %}
News
{% endblock title %}

{% block content %}
    <h1>Все новости</h1>
    <form action="" method="get">
        {{filterset.form.as_p}}
        <input type="submit" value="Найти">
    </form>
    <hr>
    {% if news %}
        <table>
            <tr>
                <td>Название</td>
                <td>Описание</td>
                <td>Категория</td>
                <td>Дата Выпуска</td>
            </tr>
            {% for new in news %}
            <tr>
                <td>{{ new.name|truncatechars:10|censor }}</td>
                <td>{{ new.description| truncatechars:15|censor }}</td>
                <td>{{ new.category}}</td>
                <td>{{ new.release_date}}</td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей пока нет!</h2>
   {% endif %}

    {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

Project/templates/product.html
{% extends 'flatpages/default.html'%}


{% block title %}
Product
{% endblock title %}

{% block content %}
    <h2> {{ time_now|date:'M d Y'}}</h2>
    <h2>Новости:{{product.name}}</h2>
    <h5>{{product.description}}</h5>
{% endblock content %}

Project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

Project/templates/product_edit.html
{% extends 'flatpages/default.html' %}

{% block conent %}
<h1>Товары</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Save"/>
</form>
{% endblock conent %}

Project/templates/products.html
{% extends 'flatpages/default.html' %}

{% load custom_filter %}
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}

{% block content %}
   <h1>Все товары</h1>

   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>

   <hr>
   {% if products %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Категория</td>
               <td>Цена</td>
               <td>Количество</td>
           </tr>

           {% for product in products %}
           <tr>
               <td>{{ product.name }}</td>
               <td>{{ product.description|truncatechars:15 }}</td>
               <td>{{ product.category.name }}</td>
               <td>{{ product.price|currency }}</td>
               <td>{{ product.quantity }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Товаров нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}